[package]
name = "maarch64-android"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "maarch64"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "maarch64-android"
path = "src/main.rs"

[dependencies]
maarch64-core = { path = "../core" }
maarch64-thunks = { path = "../thunks" }
clap = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
zip = "2.1"
anyhow = "1.0"
dex = "0.5"
object = { workspace = true }
